# Project version
version=0.6.1-SNAPSHOT

# Kotlin
kotlin.version=2.3.21
kotlin.code.style=official

# Dependencies
koin.version=4.2.2
junit.version=5.14.4
assertk.version=0.28.1
coroutines.version=1.11.0

# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.daemon.jvmargs=-Xmx2048m
